export const UTILITY_DI_TYPES = {
   Express: 'Express',
   Session: 'Session',
   GameBoardFactory: 'GameBoardFactory',
   GameBoard: 'GameBoard',
   GameBoardStore: 'GameBoardStore',
   GameBoardService: 'GameBoardService',
   CommandBus: 'CommandBus',
   EventBus: 'EventBus',
   UuidGenerator: 'UuidGenerator',
   V1UuidGenerator: 'V1UuidGenerator',
   V1UuidOptions: 'V1UuidOptions',
   V4UuidGenerator: 'V4UuidGenerator',
   V4UuidOptions: 'V4UuidOptions',
   RandomGenerator: 'RandomGenerator',
}